### ISSUE TITLE
1 or more jobs timing out often (knapsack pro split suite, 14 jobs)

### ISSUE THREAD

**Issue by partounian** [codecov/codecov-ruby#101]
We have started using https://knapsackpro.com/ with GitHub Actions and we run 14 jobs. We are using [Queue Mode](https://docs.knapsackpro.com/2020/how-to-speed-up-ruby-and-javascript-tests-with-ci-parallelisation#dynamic-tests-split), along with [split by individual tests (it) in certain situations](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it).

I often have 1 job time out, though I've also seen multiple time out.

The last step of the GitHub Action is:

```
    - name: Upload coverage results
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bin/rake codecov:upload
```
